# Generated by Django 6.0.6 on 2026-06-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='فیزیک پروژه (متراژ کل)')),
                ('price_per_meter', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر متر')),
                ('total_capital', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='سرمایه کل')),
                ('predicted_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='پیش بینی سود (%)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('predicted_end_date', models.DateField(verbose_name='پیش بینی تاریخ خاتمه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نکته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'نکته پروژه',
                'verbose_name_plural': 'نکات پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('predicted', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='پیش بینی (%)')),
                ('actual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='واقعی (%)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'پیشرفت پروژه',
                'verbose_name_plural': 'پیشرفت پروژه\u200cها',
            },
        ),
    ]
