# Generated by Django 6.0.6 on 2026-06-11 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ خریداری شده')),
                ('price_per_meter', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر متر در زمان خرید')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ کل خرید')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('cancelled', 'انصراف داده'), ('sold', 'فروخته شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='projects.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_price_per_meter', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر متر در زمان انصراف')),
                ('total_refund', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ بازگشتی')),
                ('penalty', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='کسر کارمزد (0.5%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انصراف')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'انصراف',
                'verbose_name_plural': 'انصراف\u200cها',
            },
        ),
    ]
